# DiscourseMap Configuration File
# Copy this file to config.yaml and modify as needed

# Target configuration
target:
  url: "https://meta.discourse.org"  # Target Discourse forum URL

# Optimized scan settings for better performance
threads: 20  # Increased for better concurrency
timeout: 7   # Reduced timeout for faster scanning
delay: 0.05  # Significantly reduced delay
user_agent: "DiscourseMap/1.2.0"

# Proxy settings (optional)
# proxy: "http://127.0.0.1:8080"

# SSL settings
verify_ssl: true

# Modules to run (if not specified via command line)
modules:
  - info
  - vuln
  - endpoint
  - user
  # - cve  # Uncomment for CVE scanning
  # - plugin_detection
  # - plugin_bruteforce
  # - api
  # - auth
  # - config
  # - crypto
  # - network
  # - plugin
  # - compliance

# Output settings
output:
  format: json  # json, html, csv
  directory: "./reports"
  auto_timestamp: true

# Docker automation settings
automation:
  enabled: false
  targets_file: "targets.txt"
  schedule: "0 2 * * *"  # Daily at 2 AM
  notification:
    webhook_url: ""
    slack_channel: ""

# Advanced settings optimized for performance
advanced:
  max_retries: 2  # Reduced retries for speed
  rate_limit: 50  # Increased requests per second
  user_agents_rotation: true
  save_partial_results: true
  auto_resume: true
  adaptive_rate_limiting: true  # New feature
  smart_payload_testing: true   # New feature
  parallel_module_execution: false  # Will be enabled in future updates