version: '3.8'

services:
  discoursemap:
    build: .
    container_name: discoursemap-scanner
    environment:
      - DISCOURSEMAP_VERSION=2.1.0
      - PYTHONPATH=/app
    volumes:
      - ./reports:/app/reports
      - ./config:/app/config
    networks:
      - scanner-network
    restart: unless-stopped
    
  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: discoursemap-redis
    networks:
      - scanner-network
    restart: unless-stopped
    
  # Optional: PostgreSQL for result storage
  postgres:
    image: postgres:15-alpine
    container_name: discoursemap-db
    environment:
      POSTGRES_DB: discoursemap
      POSTGRES_USER: scanner
      POSTGRES_PASSWORD: scanner_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scanner-network
    restart: unless-stopped

networks:
  scanner-network:
    driver: bridge

volumes:
  postgres_data: