version: '3.8'

services:
  # Main scanner service
  discoursemap:
    build: .
    container_name: discoursemap-scanner
    volumes:
      - ./reports:/app/reports
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
      - ./targets.txt:/app/targets.txt:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
    networks:
      - scanner-network
    # Example usage:
    # docker-compose run --rm discoursemap python3 main.py -u https://forum.example.com --config config.yaml
    
  # Automated scanner with cron-like scheduling
  auto-scanner:
    build: .
    container_name: discoursemap-auto
    volumes:
      - ./reports:/app/reports
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
      - ./targets.txt:/app/targets.txt:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - SCAN_INTERVAL=${SCAN_INTERVAL:-3600}  # Default: 1 hour
    command: python3 auto_scanner.py
    networks:
      - scanner-network
    restart: unless-stopped

networks:
  scanner-network:
    driver: bridge

volumes:
  reports:
  data: