name: discoursemap
base: core22
version: '1.2.2'
summary: Discourse forum security scanner
description: |
  DiscourseMap is a comprehensive security scanner designed specifically for
  Discourse forums. It helps security professionals and forum administrators
  identify potential vulnerabilities and security issues in their Discourse
  installations.
  
  Features:
  - Plugin vulnerability detection
  - Authentication bypass testing
  - SQL injection detection
  - XSS vulnerability scanning
  - CSRF protection testing
  - File upload security checks
  - Information disclosure detection
  - Network security analysis
  - Comprehensive reporting

grade: stable
confinement: strict

parts:
  discoursemap:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ruby
      - ruby-dev
      - bundler
      - build-essential
      - libssl-dev
      - libffi-dev
    build-packages:
      - ruby
      - ruby-dev
      - bundler
      - build-essential
      - libssl-dev
      - libffi-dev
    override-build: |
      craftctl default
      # Ruby gem'lerini yükle
      cd $CRAFT_PART_SRC
      if [ -f Gemfile ]; then
        bundle config set --local path 'vendor/bundle'
        bundle install
      fi

apps:
  discoursemap:
    command: bin/discoursemap
    plugs:
      - network
      - network-bind
      - home